cambiando yml del front 5

diff --git a/.github/workflows/build-frontend-image.yml b/.github/workflows/build-frontend-image.yml
--- a/.github/workflows/build-frontend-image.yml
+++ b/.github/workflows/build-frontend-image.yml
@@ -20,7 +20,6 @@ concurrency:
 jobs:
   Deploy-Production:
     runs-on: ubuntu-24.04
-    environment: TOKEN_VERCEL
 
     steps:
       - uses: actions/checkout@v3
@@ -43,8 +42,8 @@ jobs:
           if [ -z "${{ secrets.NEXT_PUBLIC_MEDUSA_BACKEND_URL }}" ]; then
             echo "::error::Missing NEXT_PUBLIC_MEDUSA_BACKEND_URL"; exit 1
           fi
-          if [ -z "${{ secrets.NEXT_PUBLISHABLE_MEDUSA }}" ]; then
-            echo "::error::Missing NEXT_PUBLISHABLE_MEDUSA"; exit 1
+          if [ -z "${{ secrets.NEXT_PUBLIC_PUBLISHABLE_MEDUSA }}" ]; then
+            echo "::error::Missing NEXT_PUBLIC_PUBLISHABLE_MEDUSA"; exit 1
           fi
 
       - name: Build & Push image
@@ -61,7 +60,7 @@ jobs:
 
           build-args: |
             NEXT_PUBLIC_MEDUSA_BACKEND_URL=${{ secrets.NEXT_PUBLIC_MEDUSA_BACKEND_URL }}
-            NEXT_PUBLISHABLE_MEDUSA=${{ secrets.NEXT_PUBLISHABLE_MEDUSA }}
+            NEXT_PUBLIC_PUBLISHABLE_MEDUSA=${{ secrets.NEXT_PUBLIC_PUBLISHABLE_MEDUSA }}
             NEXT_PUBLIC_DEFAULT_REGION=ar
 
           secrets: |
